import {
  Anthropic,
  Aws,
  Cohere,
  DeepSeek,
  Google,
  Meta,
  Minimax,
  Mistral,
  Moonshot,
  NousResearch,
  Nvidia,
  OpenAI,
  Perplexity,
  Qwen,
  Vercel,
  XAI,
  ZAI,
} from "@lobehub/icons";

const ProviderLogos = {
  "Open AI": (size: number) => <OpenAI size={size} />,
  Openai: (size: number) => <OpenAI size={size} />,
  Anthropic: (size: number) => <Anthropic size={size} />,
  Google: (size: number) => <Google.Color size={size} />,
  Deepseek: (size: number) => <DeepSeek.Color size={size} />,
  "DeepSeek AI": (size: number) => <DeepSeek.Color size={size} />,
  Xai: (size: number) => <XAI size={size} />,
  "X AI": (size: number) => <XAI size={size} />,
  Meta: (size: number) => <Meta.Color size={size} />,
  Moonshotai: (size: number) => <Moonshot size={size} />,
  Perplexity: (size: number) => <Perplexity.Color size={size} />,
  Alibaba: (size: number) => <Qwen.Color size={size} />,
  "Alibaba Cloud": (size: number) => <Qwen.Color size={size} />,
  Moonshot: (size: number) => <Moonshot size={size} />,
  Amazon: (size: number) => <Aws.Color size={size} />,
  Cohere: (size: number) => <Cohere.Color size={size} />,
  Mistral: (size: number) => <Mistral.Color size={size} />,
  "Mistral AI": (size: number) => <Mistral.Color size={size} />,
  Zai: (size: number) => <ZAI size={size} />,
  "Minimax AI": (size: number) => <Minimax.Color size={size} />,
  "Zhipu AI": (size: number) => <ZAI size={size} />,
  Nvidia: (size: number) => <Nvidia size={size} />,
  Vercel: (size: number) => <Vercel size={size} />,
  NousResearch: (size: number) => <NousResearch size={size} />,
};

export { ProviderLogos };
