import {
  Ai21,
  AionLabs,
  Anthropic,
  Baidu,
  ByteDance,
  Cohere,
  DeepSeek,
  Featherless,
  Google,
  Infermatic,
  Inflection,
  Liquid,
  Meta,
  Microsoft,
  Minimax,
  Mistral,
  Moonshot,
  NousResearch,
  Nvidia,
  OpenAI,
  OpenRouter,
  Perplexity,
  Qwen,
  Tencent,
  Vercel,
  XAI,
  ZAI,
} from "@lobehub/icons";

const ProviderLogos = {
  ai21: (size: number) => <Ai21 size={size} />,
  aionlabs: (size: number) => <AionLabs size={size} />,
  alibaba: (size: number) => <Qwen.Color size={size} />,
  alibabacloud: (size: number) => <Qwen.Color size={size} />,
  amazon: (size: number) => <Qwen.Color size={size} />,
  anthropic: (size: number) => <Anthropic size={size} />,
  baidu: (size: number) => <Baidu.Color size={size} />,
  bytedance: (size: number) => <ByteDance.Color size={size} />,
  cohere: (size: number) => <Cohere.Color size={size} />,
  deepseek: (size: number) => <DeepSeek.Color size={size} />,
  deepseekai: (size: number) => <DeepSeek.Color size={size} />,
  featherless: (size: number) => <Featherless.Color size={size} />,
  google: (size: number) => <Google.Color size={size} />,
  infermatic: (size: number) => <Infermatic.Color size={size} />,
  inflection: (size: number) => <Inflection size={size} />,
  liquid: (size: number) => <Liquid size={size} />,
  meta: (size: number) => <Meta.Color size={size} />,
  metallama: (size: number) => <Meta.Color size={size} />,
  microsoft: (size: number) => <Microsoft size={size} />,
  minimax: (size: number) => <Minimax.Color size={size} />,
  minimaxai: (size: number) => <Minimax.Color size={size} />,
  mistral: (size: number) => <Mistral.Color size={size} />,
  mistralai: (size: number) => <Mistral.Color size={size} />,
  moonshot: (size: number) => <Moonshot size={size} />,
  moonshotai: (size: number) => <Moonshot size={size} />,
  nousresearch: (size: number) => <NousResearch size={size} />,
  nvidia: (size: number) => <Nvidia.Color size={size} />,
  openai: (size: number) => <OpenAI size={size} />,
  openrouter: (size: number) => <OpenRouter size={size} />,
  perplexity: (size: number) => <Perplexity size={size} />,
  qwen: (size: number) => <Qwen.Color size={size} />,
  tencent: (size: number) => <Tencent.Color size={size} />,
  vercel: (size: number) => <Vercel size={size} />,
  xai: (size: number) => <XAI size={size} />,
  zai: (size: number) => <ZAI size={size} />,
  zhipuai: (size: number) => <ZAI size={size} />,
};

export { ProviderLogos };
